### ISSUE TITLE
Uncaught ReferenceError: require is not defined at render.js:1

### ISSUE THREAD

**Issue by oussamabenkortbi** [fireship-io/223-electron-screen-recorder#19]
i have nodeIntegration sets to true and everything is exactly the same as your project
 
**note: cloning your project leads to success!** 
i think it has something to do with electron version

**index.js:**
`
const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  });

  // and load the index.html of the app.
  mainWindow.loadFile(path.join(__dirname, 'index.html'));

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};
`
**render.js:**
`
const { desktopCapturer, remote } = require('electron');
`

**Comment by matthewruzzi** [comment]
I think it has something to do with [this](https://github.com/electron/electron/issues/23506) in Electron 12 
https://github.com/electron/electron/releases/tag/v12.0.0
https://github.com/electron/electron/issues/23506

**Comment by matthewruzzi** [comment]
`nodeIntegration: true`
should be replaced with 
`contextIsolation: false`

**Comment by dankoller112** [comment]
I have the same issue and also replaced `nodeIntegration: true` with `contextIsolation: false` but I still get the "Uncaught ReferenceError: require is not defined" error. Any further ideas?

**Comment by dikayx** [comment]
I could fix that issue. In newer versions of electron you need to add `enableRemoteModule: true` to your index.js. Worked just fine for me. [Read here](https://github.com/electron/electron/issues/21408)

**Comment by koushikpuppala** [comment]
> I could fix that issue. In newer versions of electron you need to add `enableRemoteModule: true` to your index.js. Worked just fine for me. [Read here](https://github.com/electron/electron/issues/21408)

where it should be added in index.js

**Comment by DroidZed** [comment]
> > I could fix that issue. In newer versions of electron you need to add `enableRemoteModule: true` to your index.js. Worked just fine for me. [Read here](https://github.com/electron/electron/issues/21408)
> 
> where it should be added in index.js

in here :
`js
const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      enableRemoteModule:true
    }
  });
`

**Comment by Schmalvis** [comment]
hmm, I'm seeing issues with this. Have the following in index.js

```
const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: { 
      contextIsolation: false,
      enableRemoteModule:true 
      }
  });
```
However Chrome is still erroring out with

>  Uncaught ReferenceError: require is not defined

**Comment by DroidZed** [comment]
Add the nodeIntegration: true setting and it will work.

**Comment by Schmalvis** [comment]
thanks - will try this. I had gathered that `nodeIntegration:true `had been depreciated and was to be replaced with `contextIsolation:false`

**Comment by DroidZed** [comment]
Since this tutorial is not that new, I guess you should be using a preload script or something like that to load the configuration for the app.

**Comment by dikayx** [comment]
> hmm, I'm seeing issues with this. Have the following in index.js
> 
> ```
> const createWindow = () => {
>   // Create the browser window.
>   const mainWindow = new BrowserWindow({
>     width: 800,
>     height: 600,
>     webPreferences: { 
>       contextIsolation: false,
>       enableRemoteModule:true 
>       }
>   });
> ```
> 
> However Chrome is still erroring out with
> 
> > Uncaught ReferenceError: require is not defined

I use this code and it works just fine:

```
const mainWindow = new BrowserWindow({
    width: 1000,
    height: 800,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true,
    }
  });

```
However don't forget to import require module with `require('@electron/remote/main').initialize();` to your index.js.

Add `const { BrowserWindow } = require('@electron/remote')` to the render.js process to use require dependencies.

**Comment by Schmalvis** [comment]
Thanks for this. This actually seems to work for me:

```
const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true
    }
  });
```
I'd thought from the above thread that `nodeIntegration:true` and `contextIsolation:false ` were essentially doing the same thing here (i.e. ok to use one or the other).

For info: electron is being imported into my index.js with the following code:
`const { app, BrowserWindow } = require('electron');`

and the dependencies used in render.js using the following `const { desktopCapturer, remote } = require('electron');`

Thanks for all your help. As must be painfully obvious; I'm very new to this.

**Comment by DroidZed** [comment]
This is the code that worked for me:

```js
const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true,
    }
  });
```

Note that I didn't modify the require imports...still using the default ones only change this part in the whole app.

**Comment by dikayx** [comment]
> I'd thought from the above thread that `nodeIntegration:true` and `contextIsolation:false ` were essentially doing the same thing here (i.e. ok to use one or the other).

I basically thought the same and was at your point ca. one month ago. I read a lot until I found I need to put in both lines..

> Thanks for all your help. As must be painfully obvious; I'm very new to this.

You're doing fine. Have fun coding!

**Comment by Asirimihindu** [comment]
I faced the same problem "Uncaught ReferenceError: require is not defined at render.js:1"
my mistake was filename mismatch between the file name  and its reference in index.html
i.e <script defer src="render.js" type="text/javascript"></script> in index.html

but file name was renderer1.js

**Comment by giuliohome** [comment]
I was having this issue 

```
Uncaught ReferenceError: require is not defined
    at render.js:1
```

and after fixing it as suggested above with

```js
const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {        /// <-- update this option
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true
    }
  });
```

now I'm getting:

```
Uncaught TypeError: Cannot destructure property 'Menu' of 'remote' as it is undefined.
    at render.js:2
```

corresponding to the lines 1-2

```js
const { desktopCapturer, remote } = require('electron');
const { Menu } = remote;
```

**Comment by giuliohome** [comment]
Solved like this.

renderer.js

```js
const { desktopCapturer, ipcRenderer  } = require('electron');

function menuselect(name) { console.log("renderer menu click" + name);}

ipcRenderer.on('menuselect', (event, name) => {
    menuselect(name);  
})
```

and then

```js
    const names = inputSources.map(f => f.name);
    await ipcRenderer.invoke('electron-menu', names);
```

index.js

```js
const { app, BrowserWindow, ipcMain, Menu, MenuItem } = require('electron');
```

```js
ipcMain.handle('electron-menu', async (event, names, menuselect) => {
  const videoOptionsMenu = new Menu();
  names.forEach(name => {
        videoOptionsMenu.append(new MenuItem({ 
            label: name, 
            click: () => event.sender.send('menuselect', name)
        }));
    });
  videoOptionsMenu.popup();
})
```

It does the trick, so I can remove the `enableRemoteModule: true` (that was not working for the latest Electron 15). Btw with a few more changes one could transform the render.js into a [preload.js](https://github.com/giuliohome/223-electron-screen-recorder/blob/preload/src/preload.js) so to restore to the standard values and remove also the other two preferences (`nodeIntegration` and `contextIsolation`).

**Comment by oussamabenkortbi** [comment]
solved with upgrading to electron 15

`const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true,
    }
  });`

**Comment by justingolden21** [comment]
I've got
```js
	const mainWindow = new BrowserWindow({
		width: 800,
		height: 600,
		webPreferences: {
			nodeIntegration: true,
			contextIsolation: false,
			enableRemoteModule: true,
		},
	});
```

But I'm still getting `Uncaught ReferenceError: require is not define at render.js:8:37`

Been stuck on this for nearly an hour... Why must Electron completely change everything with each release?

**Comment by giuliohome** [comment]
Look at what others have already shared years ago. Rewrite a better code according to the design principles. Possibly use a preload.js, follow the guidelines. Clone and ⭐ the helpful repositories with working examples.
And indeed the way this issue was closed is not the correct solution. My comments and my suggestions (and my pull request too) were simply ignored. Ok, now I've unsubscribed this thread.
